source 'https://rubygems.org'

ruby '3.2.2'

gem 'rails', '~> 7.1'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'bcrypt', '~> 3.1'
gem 'rack-cors'
gem 'jwt'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end
