"""
Shared helpers for InfraNest code generators.
"""

import copy
from typing import Any, Dict, List, Set, Tuple


#: Field types that never need an explicit sample value in a generated test
#: fixture, because the generated model field is always either auto-managed
#: (uuid primary keys / auto_generated uuid, auto_now / auto_now_add
#: datetime|date) or DB-nullable with no NOT NULL constraint regardless of
#: the DSL's `required` flag (plain datetime/date, boolean always gets a
#: model-level default). Relational types (foreign_key / many_to_many) are
#: handled separately via dependency_plan()/fk_fields() since they need a
#: *related instance*, not a scalar literal.
SKIP_TEST_VALUE_TYPES = {"uuid", "datetime", "date", "boolean", "foreign_key", "many_to_many"}


DEFAULT_AUTH = {
    "provider": "jwt",
    "user_model": "User",
    "required_fields": ["email", "password"],
    "optional_fields": [],
}

DEFAULT_API = {
    "base_path": "/api/v1",
    "endpoints": [],
}

DEFAULT_DEPLOYMENT = {
    "docker": {
        "port": 8000,
        "health_check": "/health",
    },
}


class BaseGenerator:
    """Common context-building and preview logic shared by all generators."""

    #: File extension used to guess a "type" for preview listings.
    language_by_extension = {
        "py": "python",
        "go": "go",
        "rb": "ruby",
        "mod": "config",
        "yml": "config",
        "yaml": "config",
        "json": "config",
        "md": "docs",
        "txt": "config",
        "env": "config",
        "": "config",
    }

    def build_context(self, spec: Dict[str, Any]) -> Dict[str, Any]:
        """Merge a parsed DSL spec with sane defaults for optional sections."""
        context = copy.deepcopy(spec)

        context.setdefault("meta", {})
        context["meta"].setdefault("name", "backend-project")
        context["meta"].setdefault("description", "Generated by InfraNest")
        context["meta"].setdefault("version", "1.0.0")
        context["meta"].setdefault("database", "postgresql")

        auth = context.get("auth") or {}
        merged_auth = {**DEFAULT_AUTH, **auth}
        context["auth"] = merged_auth

        api = context.get("api") or {}
        merged_api = {**DEFAULT_API, **api}
        context["api"] = merged_api

        deployment = context.get("deployment") or {}
        docker = {**DEFAULT_DEPLOYMENT["docker"], **deployment.get("docker", {})}
        merged_deployment = {**DEFAULT_DEPLOYMENT, **deployment}
        merged_deployment["docker"] = docker
        merged_deployment.setdefault("wsgi_server", "gunicorn")
        merged_deployment.setdefault("environment", "production")
        context["deployment"] = merged_deployment

        context.setdefault("models", {})
        context.setdefault("jobs", [])

        return context

    def _describe_file(self, path: str) -> Dict[str, str]:
        ext = path.rsplit(".", 1)[-1] if "." in path else ""
        file_type = self.language_by_extension.get(ext, "text")
        return {
            "path": path,
            "type": file_type,
            "description": self._describe_path(path),
        }

    def _describe_path(self, path: str) -> str:
        lower = path.lower()
        if "model" in lower:
            return "Data model definitions"
        if "serializer" in lower:
            return "Request/response serializers"
        if "view" in lower or "controller" in lower or "handler" in lower:
            return "Request handlers / views"
        if "url" in lower or "routes" in lower or "route" in lower:
            return "URL / route configuration"
        if "docker" in lower:
            return "Container build configuration"
        if "requirement" in lower or "gemfile" in lower or "go.mod" in lower:
            return "Dependency manifest"
        if "settings" in lower or "config" in lower:
            return "Application configuration"
        if "readme" in lower:
            return "Project documentation"
        if ".env" in lower:
            return "Environment variable template"
        if "migrat" in lower:
            return "Database migration"
        if "test" in lower or "spec" in lower:
            return "Automated tests"
        return "Generated project file"

    def preview(self, spec: Dict[str, Any]) -> Dict[str, Any]:
        """Return a lightweight listing of files without full content."""
        files = self.generate(spec)
        return {
            "files": [self._describe_file(path) for path in sorted(files.keys())],
            "file_count": len(files),
        }

    # Subclasses must implement generate()
    def generate(self, spec: Dict[str, Any]) -> Dict[str, str]:  # pragma: no cover
        raise NotImplementedError

    # -- shared planning for generated test suites --------------------------
    #
    # Every generator now emits a real automated test suite alongside the
    # application code (Django: DRF APITestCase, Go: httptest, Rails: RSpec
    # request specs). All three need the same two pieces of information -
    # "which models must exist before this one so its foreign keys are
    # satisfiable" and "which of this model's own fields need a sample
    # scalar value" - so that logic lives here once instead of being
    # reimplemented (and risking drifting out of sync) three times.

    def dependency_plan(self, models: Dict[str, Any]) -> Tuple[List[str], Set[Tuple[str, str]]]:
        """Order models so a model referenced by a foreign key is ordered
        before any model that depends on it, and identify which specific
        (model, field) foreign-key edges cannot be honored that way -
        self-references, and one edge in any circular reference chain.

        Returns (order, skip_edges). A test/fixture generator should build
        model instances in `order`, and for any foreign_key field whose
        (model_name, field_name) appears in `skip_edges`, leave it unset
        instead of eagerly constructing the related instance (doing so for
        a self-reference would recurse forever; doing so for the
        cycle-breaking edge of a circular reference would too).
        """
        deps: Dict[str, List[Tuple[str, str]]] = {name: [] for name in models}
        for model_name, model_config in models.items():
            for field_name, field_config in model_config.get("fields", {}).items():
                if field_config.get("type") != "foreign_key":
                    continue
                target = field_config.get("model")
                if target and target in models and target != model_name:
                    deps[model_name].append((field_name, target))

        order: List[str] = []
        state: Dict[str, str] = {}  # name -> 'visiting' | 'done'
        skip_edges: Set[Tuple[str, str]] = set()

        def visit(name: str) -> None:
            state[name] = "visiting"
            for field_name, target in deps.get(name, []):
                if state.get(target) == "visiting":
                    skip_edges.add((name, field_name))  # circular - break it here
                    continue
                if state.get(target) != "done":
                    visit(target)
            state[name] = "done"
            order.append(name)

        for model_name in models:
            if state.get(model_name) != "done":
                visit(model_name)

        return order, skip_edges

    def fk_fields(
        self,
        model_name: str,
        model_config: Dict[str, Any],
        models: Dict[str, Any],
        skip_edges: Set[Tuple[str, str]],
    ) -> List[Tuple[str, str]]:
        """Foreign-key fields on `model_name` that a test fixture should
        eagerly satisfy by constructing an instance of the target model:
        excludes self-references, cycle-breaking edges (see
        `dependency_plan`), and FKs pointing at a model this spec doesn't
        define (nothing to construct)."""
        result: List[Tuple[str, str]] = []
        for field_name, field_config in model_config.get("fields", {}).items():
            if field_config.get("type") != "foreign_key":
                continue
            target = field_config.get("model")
            if not target or target not in models or target == model_name:
                continue
            if (model_name, field_name) in skip_edges:
                continue
            result.append((field_name, target))
        return result

    def sample_field_names(self, model_config: Dict[str, Any]) -> List[str]:
        """Names of `model_config`'s own (non-relational) fields that a
        generated test should populate with an explicit sample value -
        i.e. everything except primary keys, auto-managed fields, and the
        types in SKIP_TEST_VALUE_TYPES (see that constant for why each of
        those is always safe to omit)."""
        names = []
        for field_name, field_config in model_config.get("fields", {}).items():
            if field_config.get("primary_key") or field_config.get("auto_generated"):
                continue
            if field_config.get("auto_now_add") or field_config.get("auto_now"):
                continue
            if field_config.get("type") in SKIP_TEST_VALUE_TYPES:
                continue
            names.append(field_name)
        return names
